version: "3.8"
services:
  db:
    image: postgres:14.3
    container_name: todo-database
    cap_add:
      - SYS_NICE
    restart: always
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgres
