name: Docker Image for GHCR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          docker login --username ${{ secrets.GH_US }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker-compose up -d --build todo-server
          docker push ghcr.io/carlosmanuel02/todo-server-ghcr:lastest